linters:
  LeadingZero:
    enabled: true
    style: include_zero

  StringQuotes:
    enabled: true
    style: double_quotes

  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false

  SelectorDepth:
    enabled: true
    max_depth: 4
