language: node_js
node_js:
  - "6"

before_install:
  - rvm install 2.3.4

install:
  - bundle install
  - npm install -g lodash marked varstream svgicons2svgfont node-gyp ttf2woff2
  - npm install -g gulp-cli
  - npm install

before_script: bin/rspec

script: bundle exec middleman build --clean

branches:
  only:
    - master
